const AssetLoader = {
    // Registry auto-generated: 2026-01-11 02:40
    // DO NOT EDIT MANUALLY - this file is regenerated by dashboard when assets are approved
    registries: {
        images: null,
        audio: null,
        vfx: null
    },
    cache: new Map(),
    basePath: 'assets/',

    /**
     * Initialize the asset loader with embedded registry data
     * (Avoids CORS issues when running from file:// protocol)
     */
    async init() {
        // Embedded image registry data (auto-generated from dashboard)
        this.registries.images = {
            assets: {
                "bg_zone_bone_valley": { "path": "images/backgrounds/zone_bone_valley_clean.png" },
                "bg_zone_crossroads": { "path": "images/backgrounds/zone_crossroads_clean.png" },
                "bg_zone_dead_woods": { "path": "images/backgrounds/zone_dead_woods_clean.png" },
                "bg_zone_home": { "path": "images/backgrounds/zone_home_clean.png" },
                "bg_zone_iron_ridge": { "path": "images/backgrounds/zone_iron_ridge_clean.png" },
                "bg_zone_mud_flats": { "path": "images/backgrounds/zone_mud_flats_clean.png" },
                "bg_zone_quarry_fields": { "path": "images/backgrounds/zone_quarry_fields_clean.png" },
                "bg_zone_scrap_yard": { "path": "images/backgrounds/zone_scrap_yard_clean.png" },
                "bg_zone_the_ruins": { "path": "images/backgrounds/zone_the_ruins_clean.png" },
                "building_industrial_01": { "path": "images/buildings/building_forge_clean.png" },
                "building_residential_01": { "path": "images/buildings/building_outpost_clean.png" },
                "building_t1_01": { "path": "images/buildings/building_forge_clean.png" },
                "building_t1_02": { "path": "images/buildings/building_outpost_clean.png" },
                "dino_ankylosaurus_base": { "path": "images/dinosaurs/dino_ankylosaurus_base_clean.png" },
                "dino_base": { "path": "images/dinosaurs/dino_parasaurolophus_base_clean.png" },
                "dino_parasaurolophus_base": { "path": "images/dinosaurs/dino_parasaurolophus_base_clean.png" },
                "dino_pteranodon_base": { "path": "images/dinosaurs/dino_pteranodon_base_clean.png" },
                "dino_spinosaurus_base": { "path": "images/dinosaurs/dino_spinosaurus_base_clean.png" },
                "dino_stegosaurus_base": { "path": "images/dinosaurs/dino_stegosaurus_base_clean.png" },
                "dino_triceratops_base": { "path": "images/dinosaurs/dino_triceratops_base_clean.png" },
                "dino_tyrannosaurus_base": { "path": "images/dinosaurs/dino_tyrannosaurus_base_clean.png" },
                "dino_velociraptor_base": { "path": "images/dinosaurs/dino_velociraptor_base_clean.png" },
                "npc_merchant_01": { "path": "images/characters/npc_merchant_quarry_clean.png" },
                "npc_merchant_02": { "path": "images/characters/npc_merchant_iron_clean.png" },
                "npc_merchant_03": { "path": "images/characters/npc_merchant_dead_clean.png" },
                "npc_merchant_04": { "path": "images/characters/npc_merchant_cross_clean.png" },
                "npc_merchant_05": { "path": "images/characters/npc_merchant_scrap_clean.png" },
                "npc_merchant_06": { "path": "images/characters/npc_merchant_mud_clean.png" },
                "npc_merchant_07": { "path": "images/characters/npc_merchant_bone_clean.png" },
                "npc_merchant_08": { "path": "images/characters/npc_merchant_ruins_clean.png" },
                "npc_merchant_bone": { "path": "images/characters/npc_merchant_bone_clean.png" },
                "npc_merchant_cross": { "path": "images/characters/npc_merchant_cross_clean.png" },
                "npc_merchant_dead": { "path": "images/characters/npc_merchant_dead_clean.png" },
                "npc_merchant_iron": { "path": "images/characters/npc_merchant_iron_clean.png" },
                "npc_merchant_mud": { "path": "images/characters/npc_merchant_mud_clean.png" },
                "npc_merchant_quarry": { "path": "images/characters/npc_merchant_quarry_clean.png" },
                "npc_merchant_ruins": { "path": "images/characters/npc_merchant_ruins_clean.png" },
                "npc_merchant_scrap": { "path": "images/characters/npc_merchant_scrap_clean.png" },
                "ui_avatar_knight": { "path": "images/characters/avatar_knight.png" },
                "ui_icon_forge": { "path": "images/ui/icon_forge_clean.png" },
                "ui_icon_inventory": { "path": "images/ui/icon_inventory_clean.png" },
                "ui_icon_lock": { "path": "images/ui/icon_lock_clean.png" },
                "ui_icon_magnet": { "path": "images/ui/icon_magnet_clean.png" },
                "ui_icon_map": { "path": "images/ui/icon_map_clean.png" },
                "ui_icon_orders": { "path": "images/ui/icon_orders_clean.png" },
                "ui_icon_rest": { "path": "images/ui/icon_rest_clean.png" },
                "ui_icon_settings": { "path": "images/ui/icon_settings_clean.png" },
                "ui_icon_shop": { "path": "images/ui/ui_icon_shop_clean.png" },
                "ui_icon_speech_bubble": { "path": "images/ui/ui_icon_speech_bubble_clean.png" },
                "ui_res_gem": { "path": "images/ui/currency_gem_clean.png" },
                "ui_res_gold": { "path": "images/ui/currency_gold_clean.png" },
                "ui_res_token": { "path": "images/ui/currency_token_clean.png" },
                "vfx_fog": { "path": "images/vfx/fog.png" },
                "vfx_fog_puff": { "path": "images/vfx/fog_dense.png" },
                "world_base_layer": { "path": "images/backgrounds/base_layer.png" },
                "world_bridge_planks": { "path": "images/environment/environment_planks.png" },
                "world_hero": { "path": "images/characters/world_hero_2_clean.png" },
                "world_island_home": { "path": "images/backgrounds/zone_home_clean.png" },
                "zone_bone_valley": { "path": "images/backgrounds/zone_bone_valley_clean.png" },
                "zone_crossroads": { "path": "images/backgrounds/zone_crossroads_clean.png" },
                "zone_dead_woods": { "path": "images/backgrounds/zone_dead_woods_clean.png" },
                "zone_iron_ridge": { "path": "images/backgrounds/zone_iron_ridge_clean.png" },
                "zone_mud_flats": { "path": "images/backgrounds/zone_mud_flats_clean.png" },
                "zone_quarry_fields": { "path": "images/backgrounds/zone_quarry_fields_clean.png" },
                "zone_scrap_yard": { "path": "images/backgrounds/zone_scrap_yard_clean.png" },
                "zone_the_ruins": { "path": "images/backgrounds/zone_the_ruins_clean.png" }
            }
        };

        // Embedded audio registry data (auto-generated from dashboard)
        this.registries.audio = {
            assets: {
                "sfx_dino_attack": { "path": "audio/dino_attack.wav", "volume": 0.8 },
                "sfx_dino_death": { "path": "audio/dino_death.wav", "volume": 0.9 },
                "sfx_dino_hurt": { "path": "audio/dino_hurt.wav", "volume": 0.7 },
                "sfx_dino_respawn": { "path": "audio/dino_respawn.wav", "volume": 0.9 },
                "sfx_dino_roar": { "path": "audio/dino_roar.wav", "volume": 1.0 },
                "sfx_hero_impact_flesh": { "path": "audio/hero_impact_flesh.wav", "volume": 0.7 },
                "sfx_hero_impact_metal": { "path": "audio/hero_impact_metal.wav", "volume": 0.7 },
                "sfx_hero_shoot": { "path": "audio/hero_shoot.wav", "volume": 0.8 },
                "sfx_hero_step": { "path": "audio/hero_step.wav", "volume": 0.3 },
                "sfx_hero_swing": { "path": "audio/hero_swing.wav", "volume": 0.6 },
                "sfx_level_up": { "path": "audio/level_up.wav", "volume": 0.8 },
                "sfx_resource_break_metal": { "path": "audio/resource_break_metal.wav", "volume": 0.8 },
                "sfx_resource_break_stone": { "path": "audio/resource_break_stone.wav", "volume": 0.8 },
                "sfx_resource_break_wood": { "path": "audio/resource_break_wood.wav", "volume": 0.8 },
                "sfx_resource_collect": { "path": "audio/resource_collect.wav", "volume": 0.6 },
                "sfx_ui_click": { "path": "audio/ui_click.wav", "volume": 0.5 },
                "sfx_ui_error": { "path": "audio/ui_error.wav", "volume": 0.5 },
                "sfx_ui_purchase": { "path": "audio/ui_purchase.wav", "volume": 0.7 },
                "sfx_ui_unlock": { "path": "audio/ui_unlock.wav", "volume": 1.0 }
            }
        };
        this.registries.vfx = { presets: {} };

        Logger.info('[AssetLoader] Registries loaded (auto-generated, ' + Object.keys(this.registries.images.assets).length + ' images, ' + Object.keys(this.registries.audio.assets).length + ' audio)');
        return true;
    },

    /**
     * Get image path by ID
     * @param {string} id - Asset ID (e.g., 'ui_btn_primary')
     * @returns {string|null} - File path or null if not found
     */
    getImagePath(id) {
        const asset = this.registries.images?.assets?.[id];
        if (!asset) {
            Logger.warn(`[AssetLoader] Image not found: ${id}, using placeholder`);
            return this.basePath + 'images/PH.png';
        }

        // SAFETY: Never allow _original assets in production
        if (asset.path.includes('_original')) {
            Logger.error(`[AssetLoader] BLOCKED: Cannot use _original asset: ${asset.path}`);
            return this.basePath + 'images/PH.png';
        }

        return this.basePath + asset.path;
    },

    /**
     * Get cached image object
     * @param {string} id
     * @returns {HTMLImageElement|null}
     */
    getImage(id) {
        return this.cache.get(id) || null;
    },

    /**
     * Create an image element with automatic fallback to PH.png on error
     * @param {string} src - Image source path
     * @param {function} onLoad - Optional callback when loaded
     * @returns {HTMLImageElement}
     */
    createImage(src, onLoad) {
        const img = new Image();
        img.onerror = () => {
            Logger.warn(`[AssetLoader] Image load failed: ${src}, using placeholder`);
            img.src = this.basePath + 'images/PH.png';
        };
        if (onLoad) {
            img.onload = onLoad;
        }
        img.src = src;
        return img;
    },

    /**
     * Get audio path by ID
     * @param {string} id - Asset ID (e.g., 'sfx_click')
     * @returns {object|null} - Audio config or null if not found
     */
    getAudio(id) {
        const asset = this.registries.audio?.assets?.[id];
        if (!asset) {
            Logger.warn(`[AssetLoader] Audio not found: ${id}`);
            return null;
        }
        return {
            path: this.basePath + asset.path,
            volume: asset.volume ?? 1,
            loop: asset.loop ?? false
        };
    },

    /**
     * Get VFX preset by ID
     * @param {string} id - Preset ID
     * @returns {object|null} - Preset config or null
     */
    getVFXPreset(id) {
        return this.registries.vfx?.presets?.[id] ?? null;
    },

    /**
     * Preload an image and cache it
     * @param {string} id - Asset ID
     * @returns {Promise<HTMLImageElement>}
     */
    async preloadImage(id) {
        if (this.cache.has(id)) {
            return this.cache.get(id);
        }

        const path = this.getImagePath(id);
        if (!path) return null;

        return new Promise((resolve) => {
            const img = new Image();
            img.onload = () => {
                this.cache.set(id, img);
                resolve(img);
            };
            img.onerror = () => {
                Logger.warn(`[AssetLoader] Image failed to load: ${path}, using placeholder`);
                const placeholder = new Image();
                placeholder.onload = () => {
                    this.cache.set(id, placeholder);
                    resolve(placeholder);
                };
                placeholder.onerror = () => {
                    resolve(null);
                };
                placeholder.src = this.basePath + 'images/PH.png';
            };
            img.src = path;
        });
    }
};

// Export for global access
window.AssetLoader = AssetLoader;
